export const SIDENAV_WIDTH = 54;
export const HOVER_MENU_WIDTH = 300;
export const SUB_HOVER_MENU_WIDTH = 400;

export const HOVER_MENU_ELEMENT_DEFAULT_COLOR = '#fff';
export const HOVER_MENU_ELEMENT_HOVER_COLOR = '#fff';
export const HOVER_MENU_ELEMENT_DEFAULT_BACKGROUND = 'transparent';
export const HOVER_MENU_ELEMENT_HOVER_BACKGROUND = '#5d5d7044';

export const SUB_HOVER_MENU_ELEMENT_DEFAULT_COLOR = '#000';
export const SUB_HOVER_MENU_ELEMENT_HOVER_COLOR = '#000';
export const SUB_HOVER_MENU_ELEMENT_DEFAULT_BACKGROUND = 'transparent';
export const SUB_HOVER_MENU_ELEMENT_HOVER_BACKGROUND = '#c8e3ffaa';